# spring:
#   application:
#     name: digital-asset-vault

#   datasource:
#     url: jdbc:postgresql://localhost:${POSTGRES_HOST_PORT:5433}/${POSTGRES_DB:digital_asset_vault}
#     username: ${POSTGRES_USER:dav}
#     password: ${POSTGRES_PASSWORD}

#   jpa:
#     hibernate:
#       ddl-auto: validate

#   flyway:
#     enabled: true

# server:
#   port: ${BACKEND_PORT:8081}

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info

spring:
  application:
    name: digital-asset-vault

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:host.docker.internal}:${POSTGRES_PORT:5433}/${POSTGRES_DB:digital_asset_vault}
    username: ${POSTGRES_USER:dav}
    password: ${POSTGRES_PASSWORD:Dav.2424}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: ${BACKEND_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info